spring.application.name=deporte
server.port=8080

# create and drop tables and sequences, loads import.sql
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update

#  mySql settings
spring.datasource.url=jdbc:mysql://db:3306/deporte?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP Connection Pool Configuration
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# Cambiado de MySQL8Dialect a MySQLDialect para Hibernate 6.x
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cargar el archivo import.sql al iniciar
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

# Configuración para Docker
spring.config.import=optional:file:.env[.properties]